export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Faq } from './faq'
export { default as Help } from './help'
export { default as Home } from './home'
export { default as Map } from './mappage'
export { default as News } from './news'
export { default as NotFound } from './notfound'
